version: '2'

services: 
  web_proxy:    
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - bloki      

  bloki:
    build: ./
    volumes: 
      - .:/code
    command: python3 manage.py runserver 0.0.0.0:8000
    expose: 
      - 8000