# Generated by Django 2.0.6 on 2018-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Errorlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('transakcja', models.CharField(max_length=50)),
                ('data', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Errorlog',
                'verbose_name_plural': 'Errorlogs',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dodania', models.TimeField(auto_now_add=True)),
                ('data_zatwierdzenia', models.TimeField(blank=True, default=None)),
                ('barcode', models.CharField(max_length=50)),
                ('zatwierdzony', models.BooleanField(default=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
            options={
                'verbose_name': 'Nesting',
                'verbose_name_plural': 'Nestings',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pianka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=10)),
                ('kolor', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Pianka',
                'verbose_name_plural': 'Piankas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='nesting',
            name='pianka',
            field=models.OneToOneField(on_delete='CASCADE', to='bloki_resztkowe.Pianka'),
        ),
    ]
