# Generated by Django 2.0.6 on 2018-06-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloki_resztkowe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nesting',
            name='data_zatwierdzenia',
            field=models.TimeField(default=None, null=True),
        ),
    ]
