# Generated by Django 2.0.6 on 2018-06-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloki_resztkowe', '0002_auto_20180617_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nesting',
            name='data_zatwierdzenia',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
