# Generated by Django 2.0.6 on 2018-06-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloki_resztkowe', '0003_auto_20180617_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nesting',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='nesting',
            name='data_zatwierdzenia',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
