# Generated by Django 2.0.6 on 2018-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloki_resztkowe', '0004_auto_20180617_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='nesting',
            name='data_zakonczenia',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nesting',
            name='zakonczony',
            field=models.BooleanField(default=False),
        ),
    ]
