# Generated by Django 2.0.6 on 2018-06-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloki_resztkowe', '0005_auto_20180617_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nesting',
            name='barcode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nesting',
            name='pianka',
            field=models.ForeignKey(on_delete='CASCADE', to='bloki_resztkowe.Pianka'),
        ),
    ]
